/**
 * Commonly used Lucide icons re-exported with consistent defaults.
 * Use `size={20}` at usage sites for consistent 20px (size-5) icons.
 */
export {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  FileInput,
  Folder,
  FolderOpen,
  HelpCircle,
  List,
  Loader2,
  Menu,
  MessageCircle,
  Monitor,
  PanelRightOpen,
  Pin,
  Plus,
  Save,
  Send,
  Smartphone,
  Square,
  Tablet,
  Trash2,
  X,
} from "lucide-react";
